source "https://rubygems.org"

gem "jekyll", "~> 4.3.3"
gem "jekyll-feed", "~> 0.17"
gem "webrick", "~> 1.8"
group :jekyll_plugins do
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
  gem "jekyll-paginate"
  gem "jekyll-sitemap"
  gem "jekyll-gist"
end
# gem "github-pages", group: :jekyll_plugins
# gem "jekyll-include-cache", group: :jekyll_plugins

# Ruby 3.4 경고 해결을 위한 gem 추가
gem "csv"
gem "base64"